### ISSUE TITLE
key.properties这个文件在哪

### ISSUE THREAD

**Issue by h-zhouwenjun** [phoenixsky/fun_android_flutter#1]

**Comment by phoenixsky** [comment]
签名文件并没有开源.两种处理方式
1. 在这里可以替换你自己的release签名.
2.  将其注释掉,直接使用debug签名.

`/android/app/build.gradle`注释以下代码
![image](https://user-images.githubusercontent.com/6359214/66925345-ca1cfc00-f05e-11e9-8c2f-ad9405292b4c.png)

![image](https://user-images.githubusercontent.com/6359214/66925412-e751ca80-f05e-11e9-8525-cdb6d86fc7bd.png)
