### ISSUE TITLE
Flutter v2.0.3 版本运行不起来

### ISSUE THREAD

**Issue by wiilsliang** [phoenixsky/fun_android_flutter#100]
<img width="1484" alt="WX20210331-151116@2x" src="https://user-images.githubusercontent.com/22042010/113104783-822e6c80-9233-11eb-85aa-31a8635a1126.png">

**Comment by wiilsliang** [comment]
最新sdk,部分API方法被移除了，所以报错了

**Comment by phoenixsky** [comment]
已更新
https://github.com/phoenixsky/fun_android_flutter/commit/9bd0b83f7e6a7a4a551e37a4a6ae1f43577b6295
