### ISSUE TITLE
大郎，该起床了

### ISSUE THREAD

**Issue by zhouxin1233** [phoenixsky/fun_android_flutter#105]
来个适配 null-safety的版本吧

**Comment by phoenixsky** [comment]
on my  way 
2.0分支已经开了

**Comment by zhouxin1233** [comment]
> on my way
> 2.0分支已经开了

2.0分支 没有用provider这个状态管理框架啊， master分支上封装的还挺好用的， 能适配下 空安全吗

**Comment by phoenixsky** [comment]
额，目前状态管理老版本使用的provider，新版本使用的getx。

老版本封装的耦合性比较高，也就没有抽取成独立的package，所以可以复制过去自己修改下。

**Comment by zhouxin1233** [comment]
不太好改
