### ISSUE TITLE
版本更新

### ISSUE THREAD

**Issue by IceWaterGuo** [phoenixsky/fun_android_flutter#15]
希望大佬：1、在设置里面加个当前版本号的展示，不然现在都不知道自己使用的当前是什么版本；2、加个APP内部版本更新功能，这样大佬增加了新功能发布了新版本，我们也好及时更新、跟进学习！

**Comment by phoenixsky** [comment]
嗯，我把android版本的内部更新加一下。

**Comment by phoenixsky** [comment]
android端已经入版本更新
