### ISSUE TITLE
home_page.dart

### ISSUE THREAD

**Issue by ezewu** [phoenixsky/fun_android_flutter#19]
home_page.dart里面SliverToBoxAdapter是一个空的，在这里有什么作用，我偿试删除了，好像也没发现问题

**Comment by phoenixsky** [comment]
具体看下[这里](https://github.com/peng8350/flutter_pulltorefresh/blob/master/notice.md#customscrollview)
主要为了解决sliverAppBar跳动的问题

**Comment by ezewu** [comment]
感谢
