### ISSUE TITLE
请问下载的演示app和源码编译出来的界面有点差别是怎么回事

### ISSUE THREAD

**Issue by xiaoyu4649** [phoenixsky/fun_android_flutter#2]
如下两个截屏，演示app的底部导航栏和顶部栏宽度比源码编译出来的高度小了点，还有就是列表项的高度也比源码编译出来的小了点，这是什么原因呢？ 使用的是相同的手机截的屏
![Screenshot_20190828_095242_cn phoenixsky wan_andr](https://user-images.githubusercontent.com/10207036/63820045-5aea2c00-c97a-11e9-8330-d47766bffd4f.jpg)

![Screenshot_20190828_095255_com xiaoyu4649 one](https://user-images.githubusercontent.com/10207036/63820053-62a9d080-c97a-11e9-86ff-145c8f110aec.jpg)

**Comment by phoenixsky** [comment]
问题已经修复,分4点解释 :
1. 现在Flutter的master分支,现在要求用到MethodChannel时,需要先调用 `WidgetsFlutterBinding.ensureInitialized()`.
2. 当时为了项目能够正确运行,将项目中的全局适配方案暂时注释掉了.而演示app中,还是之前含有适配方案的代码.所以导致了两边UI的不一致性.
3. main.dart下有一个注释掉的`main`方法.
```dart
// 当时为了解决运行问题的代码
main() async {
  WidgetsFlutterBinding.ensureInitialized()
  await StorageManager.init();
  runApp(App());
}

//之前含有全局适配的代码
main() async {
  /// 一些必备首选项的初始化,该代码中含有对'MethodChanneld`的使用,所以在master中无法运行
  await StorageManager.init();
  InnerWidgetsFlutterBinding.ensureInitialized()
    ..attachRootWidget(App())
    ..scheduleWarmUpFrame();
}
```
4. 现有代码
```dart
main() async {
  /// Flutter的master分支中,在使用'MethodChannel'之前
  /// 需要确保[WidgetsFlutterBinding]的初始化
  var widgetsBinding = InnerWidgetsFlutterBinding.ensureInitialized();

  /// 一些必备首选项的初始化
  await StorageManager.init();
  widgetsBinding
    ..attachRootWidget(App())
    ..scheduleWarmUpFrame();
}
```

btw,眼神真好.
你觉得是哪一种视觉效果更好一点

**Comment by xiaoyu4649** [comment]
截图可能看着不是很明显，手机上感觉差别比较大，个人感觉演示APP那种高度小点的效果好一些
