### ISSUE TITLE
如何适配ios13的黑暗模式

### ISSUE THREAD

**Issue by dvzhou** [phoenixsky/fun_android_flutter#20]
看您的项目里有黑暗模式的设置，怎么能和ios13中的黑暗模式关联起来呢？

**Comment by phoenixsky** [comment]
https://github.com/flutter/flutter/issues/33873
等官方吧,在日程中了
https://github.com/flutter/flutter/issues/35026

**Comment by dvzhou** [comment]
期待

**Comment by dvzhou** [comment]
有没有技术交流群，加一下呢？

**Comment by phoenixsky** [comment]
已适配Android的黑暗模式,在系统里设置为夜晚模式时,App会自动切换至黑暗模式.
iOS在Flutter更新后,应该会自动适配

**Comment by phoenixsky** [comment]
我去搞个群

**Comment by dvzhou** [comment]
看到您更新了。真厉害！ 搞个群交流起来比较方便，😋

**Comment by phoenixsky** [comment]
在文章末尾搞了个微信群,可以加一下

**Comment by LiangLuDev** [comment]
@phoenixsky 过期了。

**Comment by phoenixsky** [comment]
@LiangLuDev 已更新

**Comment by LiangLuDev** [comment]
@phoenixsky 过百了，加不了
