### ISSUE TITLE
splash页面后的广告页，没有办法动态获取，是否需要展示

### ISSUE THREAD

**Issue by itshu** [phoenixsky/fun_android_flutter#27]
splash页面后的广告页，没有办法动态获取，是否需要展示，这块我觉得是需要升级的

**Comment by phoenixsky** [comment]
目前还没有加广告的打算
你的意思是加个开关控制,是否显示那3秒的动画么?

**Comment by itshu** [comment]
因为你目前有个倒计时动画，可以作为广告，但是图片内容不是从网络获取的，没有办法判断是否展示

**Comment by phoenixsky** [comment]
暂时不打算接入广告.
