### ISSUE TITLE
收藏页面崩溃

### ISSUE THREAD

**Issue by wadewen** [phoenixsky/fun_android_flutter#28]
刚更新的最新版本
![1676711607](https://user-images.githubusercontent.com/19342903/66798080-78318480-ef3f-11e9-8d51-095368576562.jpg)

**Comment by phoenixsky** [comment]
刚看了下,wanAndroid的接口升级,增加了新的分享项目的功能
这个类目里作者的字段是空的,导致了NPE,一会发布个新版本
https://github.com/hongyangAndroid/wanandroid/issues/190

**Comment by phoenixsky** [comment]
https://github.com/hongyangAndroid/wanandroid/issues/190

**Comment by phoenixsky** [comment]
修复报错的代码已经提交.
已联系hongyan,接口增加`shareUser`字段
