### ISSUE TITLE
编译调试 Gradle报错 ProcessException: Process "xxx/fun_android_flutter/android/gradlew" exited abnormally

### ISSUE THREAD

**Issue by zxtyjx** [phoenixsky/fun_android_flutter#29]
![image](https://user-images.githubusercontent.com/6359214/66995171-1de02180-f101-11e9-9975-c29e6e0459a9.png)

请问遇到过类似的情况吗？

* Error running Gradle:
ProcessException: Process "/Users/***/Documents/ProjectCode/fun_android_flutter/android/gradlew" exited abnormally:

  Command: /Users/***/Documents/ProjectCode/fun_android_flutter/android/gradlew app:properties

Please review your Gradle project setup in the android/ folder.

gradle-wrapper.properties文件内容如下：
#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip

gradle-5.4.1-all.zip这个版本跟我其它项目的版本不一样，我应该怎么更新这个才行呢？

**Comment by phoenixsky** [comment]
最近更新升级了gradle的版本.
如果提示无法编译,可能是gradle新版本更新不下来.

可按照下图降级为对应版本
![image](https://user-images.githubusercontent.com/6359214/66994835-8549a180-f100-11e9-881e-2d760c0adef1.png)

**Comment by zxtyjx** [comment]
我根据提示信息执行命令但是会报另外一个错误，我不熟悉安卓开发能帮忙看看吗？
命令行提示命令：
/Users/***/Documents/ProjectCode/fun_android_flutter/android/gradlew app:properties

错误信息：
Project 'app' not found in root project 'fun_android_flutter'.

**Comment by phoenixsky** [comment]
就这一行提示信息?

**Comment by zxtyjx** [comment]
点击编译和调试报错如下：
![image](https://user-images.githubusercontent.com/8037264/66904170-37686700-f036-11e9-9b11-8bea609846d0.png)

根据提示执行如下命令：
/Users/zhaoxiang/Documents/ProjectCode/fun_android_flutter/android/gradlew app:properties

执行后错误信息如下：
![image](https://user-images.githubusercontent.com/8037264/66904259-5a931680-f036-11e9-87ec-410dbfceba8c.png)


我全部都粘全了，拜托看下谢谢！

**Comment by phoenixsky** [comment]
https://github.com/phoenixsky/fun_android_flutter/issues/29#issuecomment-542567281
把这个图里圈起来的两个版本 对应修改一下
修改为你其他flutter项目可以正常编译的版本

**Comment by zxtyjx** [comment]
额~~~还是不行，我修改的版本如下
![image](https://user-images.githubusercontent.com/8037264/66915594-f54a2000-f04b-11e9-950c-50dc2dbf3ba0.png)
![image](https://user-images.githubusercontent.com/8037264/66915597-f8dda700-f04b-11e9-9216-d96f200f25f1.png)

报错信息如下：
![image](https://user-images.githubusercontent.com/8037264/66915601-fc712e00-f04b-11e9-956c-6b9e1d83664a.png)

**Comment by phoenixsky** [comment]
31行附近有注释.打开看一下

**Comment by phoenixsky** [comment]
出现该问题,请参考第二条回复

**Comment by wangchunfei** [comment]
出现同样的问题，设置签名文件解决，但是打包成APK的时候还是会出现这个问题导致失败

**Comment by cavanlee** [comment]
把debug 模式下的签名配置注释掉即可。作者debug 模式下使用的是release 签名，但是又没有把签名文件放进去。

**Comment by dingfengnupt** [comment]
碰到同样的问题，按照上面步骤不能解决，其他人有碰到吗

**Comment by unclebu001** [comment]
在android/app/build.gradle 把签名注释掉。或者替换自己的签名就好
