### ISSUE TITLE
Android、iOS默认启动页后会有短暂黑屏现象，这个是什么原因导致的呢？

### ISSUE THREAD

**Issue by lcyluo** [phoenixsky/fun_android_flutter#3]
另，StructurePage中ViewStateWidget(onPressed: model.initData())应该为 ViewStateWidget(onPressed: model.initData)

**Comment by phoenixsky** [comment]
感谢提醒,`StructurePage`中,两处多余的括号已经去掉.

黑屏问题,是出在`main`方法中
```dart
 await StorageManager.init();
```
该行代码,同步执行了一些数据初始化的操作,导致UI卡在了这里.
之前初始化的数据比较少,没有感知到.

正在fix

**Comment by TimLang** [comment]
真机调试，iphone xs启动不了，进到splash页面，直接卡住了

**Comment by lcyluo** [comment]
需要在你的手机上，设置信任你自己的开发调试证书；

设置>通用>描述文件与设备管理>开发者应用

**Comment by TimLang** [comment]
> 需要在你的手机上，设置信任你自己的开发调试证书；
> 
> 设置>通用>描述文件与设备管理>开发者应用

不是这个问题，我其他项目都没问题，就这个真机黑屏，查不到原因。

**Comment by phoenixsky** [comment]
> 真机调试，iphone xs启动不了，进到splash页面，直接卡住了

@lcyluo 
你看下xcode中.这里是debug还是release?
如果是release,需要执行`flutter build ios`
![image](https://user-images.githubusercontent.com/6359214/64011104-9db02d80-cb4d-11e9-85a9-7aa67bc83d39.png)

![image](https://user-images.githubusercontent.com/6359214/64011077-91c46b80-cb4d-11e9-972b-866213a16311.png)

**Comment by TimLang** [comment]
@phoenixsky 我是debug模式，很奇怪，感觉是有个层把页面盖住了，能发送请求到服务器，但就是黑屏，模拟器一切正常。

**Comment by phoenixsky** [comment]
@TimLang  我在[release](https://github.com/phoenixsky/fun_android_flutter/releases/tag/0.1.2)加入了ipa,你用xcode,直接安装试试.我这边iPhone X max测试正常

**Comment by phoenixsky** [comment]
@lcyluo 首页闪屏问题已修复

**Comment by TimLang** [comment]
ipa安装说无效的描述文件。

**Comment by TimLang** [comment]
@phoenixsky 终于解决问题了，可以Xcode安装到真机启动了。发现是flutter的问题，pull下master分支后就好了。。我这flutter可是一周前才装的。。。
