### ISSUE TITLE
flutter初始化数据问题

### ISSUE THREAD

**Issue by zxtyjx** [phoenixsky/fun_android_flutter#30]
看了代码有个初始化的问题想咨询一下，
flutter的build是同步方法，所以在widget树构建过程中不允许出现异步返回值的操作，同时也不能更新provider,由于我运行示例程序一直报错，所以我就自己按照示例简化写了一个provider的实现，发现其实是在initState方法里调用了同步的initData方法，并且在initData方法里又去异步调用了获取数据的方法，这样如果接口比较慢这个initState方法一直执行不完，界面渲染也就会有延迟，我模拟了一个休眠5秒，导致界面5秒后才会显示出来，不知道是我写错了，还是示例程序也是这么考虑的，另外有没有flutter在界面初始化的时候初始化数据的方法呢？

**Comment by phoenixsky** [comment]
你把项目跑起来就明白了.有问题,可以加看文章末尾的微信群
