### ISSUE TITLE
0.1.9版本后更新无法覆盖安装,签名文件不一致

### ISSUE THREAD

**Issue by lzy2014love** [phoenixsky/fun_android_flutter#31]
0.1.5版本升级到0.1.10,安装时签名与上版本不一致

**Comment by phoenixsky** [comment]
起初采用的是debug的签名.上架需要,统一采用release签名.

**Comment by phoenixsky** [comment]
android 0.1.9版本之后替换了新的签名文件,导致之前版本不能覆盖安装.需要重新下载安装
