### ISSUE TITLE
是否能考虑加入统一的网络错误管理呢

### ISSUE THREAD

**Issue by s1min** [phoenixsky/fun_android_flutter#32]
当设备断网或者网络不好的时候应该提示网络错误吧，个人觉得这样体验不是很好，如下图：
![微信图片_20191017104132](https://user-images.githubusercontent.com/29031940/66973763-89a79780-f0cb-11e9-9557-41aa05a600df.jpg)
![微信图片_20191017103901](https://user-images.githubusercontent.com/29031940/66973779-92986900-f0cb-11e9-96b0-ed62cfeba8e8.jpg)

**Comment by phoenixsky** [comment]
目前没想好是否与dio彻底解耦,还是融到一起.有方案请pr

**Comment by s1min** [comment]
> 目前没想好是否与dio彻底解耦,还是融到一起.有方案请pr

我目前正在做的项目就是按大佬的这个项目的思路来的，也在考虑如何管理网络错误 XD

**Comment by phoenixsky** [comment]
已加入网络错误提示
