### ISSUE TITLE
有点卡顿

### ISSUE THREAD

**Issue by sunshu** [phoenixsky/fun_android_flutter#35]
下完项目跑起来之后，体系页面上下滑动有点卡顿，公众号页面，进入具体内容页面，也有比较明显的改动，手机是小米8se。有别的同学有类似情况吗，了解主要是什么原因吗？

**Comment by phoenixsky** [comment]
如果是debug模式运行的.是因为flutter机制的问题.ReadMe里有说明.

**Comment by phoenixsky** [comment]
`进入具体内容页面，也有比较明显的改动`
这个改动指的是?

**Comment by sunshu** [comment]
是debug了，没注意到readme
