### ISSUE TITLE
默认底部tabs切换了，pageview没有切换

### ISSUE THREAD

**Issue by F0F0FO** [phoenixsky/fun_android_flutter#37]
_selectedIndex =4;
currentIndex ==_selectedIndex;
当_selectedIndex=4；
BottomNavigationBarItem 切换了但是默认加载的页面还是首页，需要点击一次才能加载我的页面

**Comment by phoenixsky** [comment]
测试了下没有发现该问题. 
测试平台,环境是否可以贴一下
