### ISSUE TITLE
webview里面的内容很糊

### ISSUE THREAD

**Issue by guozhiqiang123** [phoenixsky/fun_android_flutter#4]
**测试手机小米6。**

1.在设置里面不开启WebViewPlugin,则打开详情页看起来字体很糊，内容显示完整
![微信图片_20190830102429](https://user-images.githubusercontent.com/20378988/63988825-974f9080-cb10-11e9-9e0b-e30c9b553cd1.png)
。
2.如果在设置中开启WebViewPlugin,则详情页右侧的内容显示不完整，字体不糊。
![微信图片_20190830102437](https://user-images.githubusercontent.com/20378988/63988854-b2ba9b80-cb10-11e9-9230-c067b66f0036.png)

**Comment by phoenixsky** [comment]
@guozhiqiang123 用模拟器1080P的分辨率没有问题,但是用同事的手机,确实发现了该问题.应该是flutter相关bug,我找找对应issues.

**Comment by phoenixsky** [comment]
原因是我采用了修改`ViewConfiguration`来进行屏幕适配的方案.
![image](https://user-images.githubusercontent.com/6359214/64153543-ae201b00-ce61-11e9-93ed-2923adf62846.png)
因为手动调整了设备像素比.导致了该问题.
目前除了不采用这套适配方案,还没有找到合适的方法.

```dart
//  InnerWidgetsFlutterBinding.ensureInitialized()
//    ..attachRootWidget(App(future: StorageManager.init()))
//    ..scheduleWarmUpFrame();

  WidgetsFlutterBinding.ensureInitialized()
    ..attachRootWidget(App(future: StorageManager.init()))
    ..scheduleWarmUpFrame();
```

**Comment by guozhiqiang123** [comment]
好吧

**Comment by dongchunhai** [comment]
虽然不是很了解这个屏幕适配方案，但是感觉可以参考下flutter_screenutil的方案

**Comment by phoenixsky** [comment]
@dongchunhai  侵入性太强.所有的size都要包裹`ScreenUtil.getInstance().setSp(24)` .用起来太麻烦

**Comment by dongchunhai** [comment]
> @phoenixsky 
修改屏幕像素密度的适配方案在ios上适配情况怎样呢？和android类似吗？

**Comment by phoenixsky** [comment]
iOS没发现有什么问题

**Comment by phoenixsky** [comment]
已经移除之前的屏幕适配方式
