### ISSUE TITLE
部分手机上（MIX 3），进入启动页的时候，会黑一下屏，推测是 main 中调用 StorageManage 初始化 getTemporaryDirectory() 时，"太耗时" 的问题？

### ISSUE THREAD

**Issue by yuehongjie** [phoenixsky/fun_android_flutter#40]

**Comment by phoenixsky** [comment]
什么环境?
自己打包的还是下载的?
release还是debug ?
flutter sdk 什么版本 ?

Flutter团队已经对第一帧的问题进行过处理.release下
flutter端如果没有渲染ui,会一直在nativie的splash页面. 直到渲染帧.

所以StorageManage的耗时操作没有关系

**Comment by yuehongjie** [comment]
我是 debug 模式直接运行的，sdk 版本为 Flutter 1.9.1+hotfix.4 • channel stable

是因为 debug 模式，没有做优化吗？

**Comment by phoenixsky** [comment]
https://github.com/flutter/flutter/issues/39494
