### ISSUE TITLE
建议去除flutter_webview_plugin

### ISSUE THREAD

**Issue by gitfornncn** [phoenixsky/fun_android_flutter#43]
1.flutter_webview_plugin社区插件不是widget，造成无法在其组件上定制某些按钮
2.resize时有250毫秒的延迟（作者解释说为了避免同时有多个resize的请求）

**Comment by phoenixsky** [comment]
感谢反馈,不过这个开源项目本身就是让学习用的.
最初加入`webview_flutter`和`flutter_webview_plugin`两个webview插件就是让大家有不同的选择,可以分别体验两个插件后,在自己的项目中选择合适的.不喜欢可以再设置里切换为`webview_flutter`.
同样`webview_flutter`目前也有一些功能上的问题,需要用`flutter_webview_plugin`来补充
