### ISSUE TITLE
关于重写animatedlist.dart导致的编译问题如何解决？

### ISSUE THREAD

**Issue by liuyh927** [phoenixsky/fun_android_flutter#44]
Compiler message:
lib/ui/page/favourite_list_page.dart:11:1: Error: 'SliverAnimatedListState' is imported from both 'package:flutter/src/widgets/animated_list.dart' and 'package:fun_android/flutter/refresh_animatedlist.dart'.
import 'package:fun_android/flutter/refresh_animatedlist.dart';

**Comment by phoenixsky** [comment]
在import部分将冲突的类hide掉

**Comment by liuyh927** [comment]
> 在import部分将冲突的类hide掉
我想说明的是，这个类被重写了。所以不是引入而是说应该不需要引入这个类，只是编译发现这个问题，无法编译通过

**Comment by phoenixsky** [comment]
因为flutter SDK更新 
部分类目录有所调整 比如SliverAnimatedList，SliverAnimatedListState迁移到了Material包下
所以将Material包下冲突的类hide掉 
如
```dart
import 'package:flutter/material.dart' hide SliverAnimatedListState,SliverAnimatedList;
```
项目中重写源码的部分 比如banner  search  和SliverAnimatedList等 如果冲突都需要手动hide

**Comment by sky126** [comment]
微信群加不进去了

**Comment by liyujiang-gzu** [comment]
```dart
import 'package:flutter/material.dart'
    hide SliverAnimatedListState, SliverAnimatedList;
import 'package:flutter_slidable/flutter_slidable.dart';
import 'package:fun_android/generated/i18n.dart';
```
除了`SliverAnimatedListState,SliverAnimatedList`，还有`search.dart`这个编译错误(缺少TargetPlatform.macOS)：
```dart
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
        routeName = '';
        break;
      case TargetPlatform.android:
      case TargetPlatform.fuchsia:
        routeName = searchFieldLabel;
        break;
      default:
        break;
    }
```

**Comment by liyujiang-gzu** [comment]
fix it, see [PR#45](https://github.com/phoenixsky/fun_android_flutter/pull/45)

**Comment by guotie** [comment]
error: 'SliverAnimatedList' isn't a function. (invocation_of_non_function at [fun_android] lib\ui\page\favourite_list_page.dart:77)

error: The name 'SliverAnimatedList' is defined in the libraries 'package:flutter/src/widgets/animated_list.dart' and 'package:fun_android/flutter/refresh_animatedlist.dart'. (ambiguous_import at [fun_android] lib\ui\page\favourite_list_page.dart:77)
