### ISSUE TITLE
MemoryLeakMonitor.jar is not exist 

### ISSUE THREAD

**Issue by helloworkcupid** [phoenixsky/fun_android_flutter#46]
华为手机  android 8.1 总是报这个错， 
MemoryLeakMonitor.jar is not exist!
Could not get cmap table size!
[ERROR:flutter/shell/gpu/gpu_surface_gl.cc(58)] Failed to setup Skia Gr context. // 出结果

添加 --enable-software-rendering参数运行

flutter run --enable-software-rendering
 
能够跑起来，但是杀死应用再启动会崩溃，或者点击 ListView的item 也会崩溃，报错信息依然如故。请问有没有好的办法解决。

**Comment by phoenixsky** [comment]
好像好几个这样的issue了,等官方解决吧
https://github.com/flutter/flutter/issues/46866
