### ISSUE TITLE
在AS中debug跑报编译错误

### ISSUE THREAD

**Issue by dalu8888** [phoenixsky/fun_android_flutter#47]
环境：gradle6.0.1，flutter1.12最新稳定版
报错信息：
Compiler message:
/F:/flutter1.12/.pub-cache/hosted/pub.flutter-io.cn/cached_network_image-1.1.1/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
/F:/flutter1.12/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'F:\flutter1.12\packages\flutter_tools\gradle\flutter.gradle' line: 780
![报错](https://user-images.githubusercontent.com/22486763/71158018-16aece80-227e-11ea-9d64-2ae1dfdafefc.png)

**Comment by geekcarl** [comment]
升级依赖库能解决这个问题，like this ：
cached_network_image: ^2.0.0-rc

**Comment by phoenixsky** [comment]
已适配SDK版本为stable, v1.12.13+hotfix.5
