### ISSUE TITLE
Provider好像没控制好？？？

### ISSUE THREAD

**Issue by Aillumine** [phoenixsky/fun_android_flutter#50]
每次页面切换后，重新回去，会反复调用build，两三次，感觉不太对啊。。。

**Comment by Aillumine** [comment]
举个例子，首页点搜索，会调用一次build，然后把搜索关了，返回首页，又会调用一次。。。

**Comment by phoenixsky** [comment]
https://github.com/phoenixsky/fun_android_flutter/issues/8

**Comment by phoenixsky** [comment]
Duplicate of #8

**Comment by Aillumine** [comment]
> #8

不是的，你在HomePage里build里打个断点，然后去点一下搜索，然后再返回，会调用两次，进搜索一次，返回一次

**Comment by phoenixsky** [comment]
你写个demo不要用provider试试

**Comment by Aillumine** [comment]
> 你写个demo不要用provider试试

https://github.com/kaina404/FlutterDouBan,这个我运行了就不会的，没用Provider

**Comment by phoenixsky** [comment]
影响flutter页面widget调用build的方法有很多.  
单纯的跳转路由,弹出dialog什么的都可以导致build的调用
你自己随便写个页面,加个按钮 调用showModalBottomSheet 就会导致页面的疯狂build

跟provider没有关系

**Comment by Aillumine** [comment]
噢，好吧，非常感谢，可以问下，咱这个是啥影响的啊？刚学，见笑了

**Comment by phoenixsky** [comment]
https://stackoverflow.com/questions/52249578/how-to-deal-with-unwanted-widget-build

具体意思
在Flutter中，Build方法的设计方式是pure/without side effects，书面意思是无副作用的/纯粹的，简单点理解我们可以将其含义看作不会对外部的方法或者变量产生影响的。这是因为许多外部因素能够触发新的小部件的构建，例如这些情况：

 - 路由的pop/push，用于进/出页面的动画
 - 屏幕大小的调整，通常是由于键盘弹出或者屏幕方向改变、
 - 父级Widget重新创建它的子Widget
 - 窗口小部件依赖于（Class.of(context)模式）更改的InheritedWidget

**Comment by Aillumine** [comment]
> https://stackoverflow.com/questions/52249578/how-to-deal-with-unwanted-widget-build
> 
> 具体意思
> 在Flutter中，Build方法的设计方式是pure/without side effects，书面意思是无副作用的/纯粹的，简单点理解我们可以将其含义看作不会对外部的方法或者变量产生影响的。这是因为许多外部因素能够触发新的小部件的构建，例如这些情况：
> 
> * 路由的pop/push，用于进/出页面的动画
> * 屏幕大小的调整，通常是由于键盘弹出或者屏幕方向改变、
> * 父级Widget重新创建它的子Widget
> * 窗口小部件依赖于（Class.of(context)模式）更改的InheritedWidget

但是咱这个刚好主页页面不是很复杂，肉眼看不出来，每次进一篇文章，再返回，调用一次build，就会渲染一次页面，如果页面复杂了，就会看到，每次都刷新一遍，不是很好啊，体验很差，前辈，怎么解决这问题？可以加个微信或者啥交流一下吗？

**Comment by phoenixsky** [comment]
上边解释的不清楚么?
调用build不是问题. Flutter的设计使然.跟我们的app没有关系
你自己写个demo,动动手看看,好吗?

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Page1(),
    );
  }
}

class Page1 extends StatefulWidget {
  @override
  _Page1State createState() => _Page1State();
}

class _Page1State extends State<Page1> {
  @override
  Widget build(BuildContext context) {
    print('build Page1');
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Navigator.push(
              context, new MaterialPageRoute(builder: (context) => Page2()));
        },
        child: Icon(Icons.add),
      ),
    );
  }
}

class Page2 extends StatefulWidget {
  @override
  _Page2State createState() => _Page2State();
}

class _Page2State extends State<Page2> {
  @override
  Widget build(BuildContext context) {
    print('build Page2');
    return Scaffold(
      appBar: AppBar(),
    );
  }
}

```



另外多次调用build并不一定会去渲染页面. 可以去了解一些flutter的渲染原理

**Comment by Aillumine** [comment]
> 上边解释的不清楚么?
> 调用build不是问题. Flutter的设计使然.跟我们的app没有关系
> 你自己写个demo,动动手看看,好吗?
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       home: Page1(),
>     );
>   }
> }
> 
> class Page1 extends StatefulWidget {
>   @override
>   _Page1State createState() => _Page1State();
> }
> 
> class _Page1State extends State<Page1> {
>   @override
>   Widget build(BuildContext context) {
>     print('build Page1');
>     return Scaffold(
>       floatingActionButton: FloatingActionButton(
>         onPressed: () {
>           Navigator.push(
>               context, new MaterialPageRoute(builder: (context) => Page2()));
>         },
>         child: Icon(Icons.add),
>       ),
>     );
>   }
> }
> 
> class Page2 extends StatefulWidget {
>   @override
>   _Page2State createState() => _Page2State();
> }
> 
> class _Page2State extends State<Page2> {
>   @override
>   Widget build(BuildContext context) {
>     print('build Page2');
>     return Scaffold(
>       appBar: AppBar(),
>     );
>   }
> }
> ```
> 
> 另外多次调用build并不一定会去渲染页面. 可以去了解一些flutter的渲染原理

好的，非常感谢耐心解答。去补一下基础
