### ISSUE TITLE
修改代码之后，运行的结果还是以前的代码样式

### ISSUE THREAD

**Issue by wcrhjc123** [phoenixsky/fun_android_flutter#51]
您好，有个问题就是把这个项目down下来之后，修改部分代码，运行后，有变化，然后杀掉app之后，点击图标进入。又变回之前的代码样式了、想请问一下是有啥问题么

**Comment by phoenixsky** [comment]
我也发现过这个问题,具体忘了方案了😂
你把模拟器的app删了再把outputs的apk也删了.清下缓存试试

**Comment by wcrhjc123** [comment]
我试了一下，用 flutter项目打开会这样，但是用xcode打开IOS Module或者用Android Studio打开单独的Android Module运行后是没问题的。比较神奇
