### ISSUE TITLE
response  data 没有反序列化，我再加个才行，为什么。。。

### ISSUE THREAD

**Issue by TrumpUSA** [phoenixsky/fun_android_flutter#53]
`  @override
  onResponse(Response response) {
    debugPrint('---api-response--->resp----->${response.data}');
    //response  换了API，报文格式不一样，发现response没有反序列化，是什么原因，他在哪里处理的反序列化
    Map<String, dynamic> user = json.decode(response.data);

    debugPrint(user['msg'].toString());

    ResponseData respData = ResponseData.fromJson(response.data);
    if (respData.success) {
      response.data = respData.data;
      return http.resolve(response);
    } else {
      if (respData.code == -1001) {
        // 如果cookie过期,需要清除本地存储的登录信息
        // StorageManager.localStorage.deleteItem(UserModel.keyUser);
        throw const UnAuthorizedException(); // 需要登录
      } else {
        throw NotSuccessException.fromRespData(respData);
      }
    }
  }
}`

**Comment by phoenixsky** [comment]
没看明白

**Comment by TrumpUSA** [comment]
response.data  是个字符串。需要我Map<String, dynamic> user = json.decode(response.data);  这样一下才可以。（换成我的login API）

**Comment by TrumpUSA** [comment]
为啥用 https://www.wanandroid.com/的api 不需要Map<String, dynamic> user = json.decode(response.data);   他这个 response.data   在哪里做的  json.decode

**Comment by phoenixsky** [comment]
dio处理的string 转json

**Comment by TrumpUSA** [comment]
dio 没转，直接String 扔 过来的。response.data是个String....   。。。
