### ISSUE TITLE
splash页面，倒计时动画

### ISSUE THREAD

**Issue by dnvyygy** [phoenixsky/fun_android_flutter#55]
_animation.addStatusListener((status) {
      if (status == AnimationStatus.completed) {
        _logoController.reverse();
      } else if (status == AnimationStatus.dismissed) {
        _logoController.forward();
      }
    });
    _logoController.forward();
为什么需要再做判断？
 _countdownController =
        AnimationController(vsync: this, duration: Duration(seconds: 4));
    _countdownController.forward();
这里不是已经开始了吗？
求告知，谢谢

**Comment by phoenixsky** [comment]
循环播放
