### ISSUE TITLE
ios 启动页短暂黑屏

### ISSUE THREAD

**Issue by liupeng826** [phoenixsky/fun_android_flutter#57]
Flutter app 在ios平台设置启动图以后启动app 在启动页和splash页之间为什么会有短暂的黑屏

**Comment by phoenixsky** [comment]
https://github.com/flutter/flutter/issues/39494

**Comment by liu1013269528** [comment]
我自己研究了一个相对友好的避免 iOS 黑屏的方式，我 localstorage 的初始化，放到 flashpage 中，这样可以避免出现黑屏出现，其实主要就是 
`localStorage = LocalStorage('LocalStorage');
    await localStorage.ready;` 比较耗时间。

**Comment by phoenixsky** [comment]
@liu1013269528 这个方案治标不治本，耗时操作是我故意在flutter引擎初始化时加入的。

flutter sdk在设计之初是打算在 flutter这边有输出第一帧图像时，才由native的闪屏切换到flutter，这样不管flutter方面在初始化时耗时多久，都会先一直显示native端的图像，直到flutter开始输出图像。
但是在后来的几次sdk的更新中，这个[issue39494](https://github.com/flutter/flutter/issues/39494)反复出现问题。
目前该issue已经被关闭，可以更新至已修复版本的sdk，然后在release环境测试。
