### ISSUE TITLE
关于屏幕适配请教

### ISSUE THREAD

**Issue by Pluto1219** [phoenixsky/fun_android_flutter#61]
萌新看了大神的代码受益匪浅， 实际开发中也用的贼爽， 现在碰到了一些适配的问题。
以下是我适配代码
![image](https://user-images.githubusercontent.com/15402976/76488606-ec297780-6460-11ea-877c-7297a5dbf077.png)

但是我并未在大神的代码中发现各处适配  请问大神是怎么做的 （另外我在ipad中运行大神的项目 ， 也是很完美， 只是四周留黑） 
萌新真心请教大神  谢谢

**Comment by Pluto1219** [comment]
请求加入组织  二维码已失效

**Comment by phoenixsky** [comment]
适配的代码存在一些对platform_view的影响了所以移除了。目前没有找到更好的适配方式

**Comment by Pluto1219** [comment]
@phoenixsky 微信群可以再发一下吗

**Comment by phoenixsky** [comment]
加入我微信（GitHub用户名）备注fun flutter，拉你进群

**Comment by Pluto1219** [comment]
@phoenixsky 加了
