### ISSUE TITLE
生成web项目，用iis做服务器，chorme打开空白页

### ISSUE THREAD

**Issue by yaxino** [phoenixsky/fun_android_flutter#62]
你好，

我今天下载下来代码，然后 用 flutter create . 添加了web项目 。
然后执行 flutter build web 。
能够正确build出web 文件。
我把这些文件放到 iis web server 上。
用 chome 打开，居然是空白的。
不知道 是什么问题？
你们试过 生成web项目吗 ？
还请你们也生成一下。 这样 web,android,ios就都支持了。
谢谢

**Comment by phoenixsky** [comment]
该项目没有适配web端，短期也没有意图
