### ISSUE TITLE
首页banner高度是怎么计算的

### ISSUE THREAD

**Issue by TimLang** [phoenixsky/fun_android_flutter#63]
首页看到banner高度是这样的：

bannerHeight = MediaQuery.of(context).size.width * 5 / 11;

请问这是依据什么呢，MediaQuery.of(context).size是拿到实际的像素值吧，不做前端的望解惑。。谢谢。

**Comment by phoenixsky** [comment]
根据多种设备，结合iOS和Android不同的通知栏，试出来比较合适的一个高度，没有科学依据
