### ISSUE TITLE
why

### ISSUE THREAD

**Issue by hqxluoyang** [phoenixsky/fun_android_flutter#64]
The current Flutter SDK version is 1.10.15-pre.424.

Because fun_android depends on provider >=4.0.0-dev which requires Flutter SDK version >=1.12.1, version solving failed.
pub get failed (1; Because fun_android depends on provider >=4.0.0-dev which requires Flutter SDK version >=1.12.1, version solving failed.)

**Comment by phoenixsky** [comment]
update your flutter sdk
