### ISSUE TITLE
在登录页，当输入框获取到焦点后，在手机设置中来回切换显示模式（深色模式）时，会报Failed assertion: line 745 pos 12: 'attached': is not true 的错，具体如图片中所示

### ISSUE THREAD

**Issue by dvzhou** [phoenixsky/fun_android_flutter#66]
<img width="332" alt="WX20200402-130437@2x" src="https://user-images.githubusercontent.com/40446804/78212688-0cd67180-74e3-11ea-85b5-5dbba5d42b4c.png">
<img width="988" alt="WX20200402-130458@2x" src="https://user-images.githubusercontent.com/40446804/78212693-0f38cb80-74e3-11ea-9d5d-1f3b1716c163.png">

**Comment by phoenixsky** [comment]
参考https://github.com/flutter/flutter/issues/40755
可参考 https://github.com/flutter/flutter/issues/40755#issuecomment-586967814 的总结。
中心思想为，bug修复了，merge在v1.13.6版本里，你可以手动更新sdk
另外这个assert问题在release里并不会出现
