### ISSUE TITLE
版本更新问题

### ISSUE THREAD

**Issue by 390057892** [phoenixsky/fun_android_flutter#67]
我将version改为0.1.4 为什么检测不到新版本啊 。报了一个错误我也不太清楚是否和更新有关 NotExpectedException{respData: Incorrect app key}  麻烦作者告知下。我想看下检测更新的流程和逻辑。

**Comment by phoenixsky** [comment]
这个说来话长，我用的蒲公英的服务，结果他们家数据丢失了。。。
所有app需要重新再上上架，之前的app key失效了。
我把代码更新一下，换成新的app key，你直接更新一下就行，再改版本号测试。

更新这块我这里处理的并不好，现在应该有更好的库，不过可以参考一下。
