### ISSUE TITLE
ipa是哪个文件呀 

### ISSUE THREAD

**Issue by LiangLuDev** [phoenixsky/fun_android_flutter#7]

**Comment by phoenixsky** [comment]
已经上架AppStore.
[![Get it from iTunes](https://lisk.io/assets/svg/download_on_the_app_store_badge.svg)](https://apps.apple.com/cn/app/id1477299503)
> 为了通过审核,将`android`等相关文字替换为了`iOS`,以及关闭了详情功能.在`2019年9月3日9点30分`后可正常使用.
