### ISSUE TITLE
升级到 flutter_html 1.0.0 失败

### ISSUE THREAD

**Issue by zf8848** [phoenixsky/fun_android_flutter#73]
升级到 flutter_html 1.0.0 失败

在 article_list_item.dart 中:

Widget build(BuildContext context) {
    return Html(
      padding: EdgeInsets.symmetric(vertical: 5),
      useRichText: false,
      data: title,
      defaultTextStyle: Theme.of(context).textTheme.subtitle2,)

padding,useRichText,defaultTextStyle 没有相关参数名.

**Comment by phoenixsky** [comment]
因为该插件有breakChange，已移除相关样式代码
