### ISSUE TITLE
多次build问题请教

### ISSUE THREAD

**Issue by TruthKeeper** [phoenixsky/fun_android_flutter#78]
你好，拜读了源码发现ProviderWidget里面直接包裹了一个Consumer，这样的话model刷新的话，这个Consumer作为节点也会重新build里面的组件吧，这样是不是失去了作为Consumer局部刷新的意义？

**Comment by phoenixsky** [comment]
ProviderWidget的设计的目的 就是在model刷新的话 重新build的组件的呀

**Comment by zero-li** [comment]
> 你好，拜读了源码发现ProviderWidget里面直接包裹了一个Consumer，这样的话model刷新的话，这个Consumer作为节点也会重新build里面的组件吧，这样是不是失去了作为Consumer局部刷新的意义？

你的疑问是对的，
 ProviderWidget 封装不正确，失去了作为Consumer局部刷新的意义，正确用法如下图：
![image](https://user-images.githubusercontent.com/11586926/119311632-e43fa700-bca3-11eb-8325-9f4caecd5a6b.png)

**Comment by phoenixsky** [comment]
感谢反馈。
provideidget设计的初衷，是为了方便页面级别的wigdet设计的，特别是listview。所以才会用consumer来包裹整个list。

另外，拿登录页面来讲，providerWidget包裹的本身就是局部的widget。

他的目的是封装了，一些页面状态，初始化加载回调。
就可以在listview等本身这个widget就需要更新的情况

其他局部更新的widget，也会使用单独的consumer



zero-li ***@***.***>于2021年5月24日 周一15:27写道：

**Comment by hlj2722** [comment]
在使用 ProviderWidget 包裹的Widget中修改一个变量后，其它共享这个变量的页面，无法实时更新这个变量的值。
