### ISSUE TITLE
ProviderWidget 会导致没有要的build

### ISSUE THREAD

**Issue by shingohu** [phoenixsky/fun_android_flutter#8]
可以打印下didUpdateWidget 方法,会发现很多没必要的build,同时也会创建新的viewmodel

**Comment by phoenixsky** [comment]
可否贴一个小的demo.没有太明白,是在初次加载的情况下就会多次build么?
因为Flutter框架在`Debug Mode`下,本身就会存在多次`build`的情况.比如
```dart
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('app build');
    return Container(color: Colors.red);
  }
}
```
### Debug运行模式下这里存在三种情况:
1.  第一次运行也就是`flutter run`或者`flutter run --debug`,会打印两次
![image](https://user-images.githubusercontent.com/6359214/64317071-311fad80-cfe9-11e9-8e3c-f3c501a003c6.png)
2.  执行hotload 会打印一次
![image](https://user-images.githubusercontent.com/6359214/64317103-4563aa80-cfe9-11e9-9c2d-6be7fef6fbe0.png)
3. 执行hot restart 会打印两次
![image](https://user-images.githubusercontent.com/6359214/64317145-61674c00-cfe9-11e9-8133-ad45348f325e.png)

### `Release`模式下,只会打印一次.
![image](https://user-images.githubusercontent.com/6359214/64317426-42b58500-cfea-11e9-8e1b-576f47e8a0cd.png)

同时我测试了在release模式下`ProviderWidget`并没有导致widget的多次build
![image](https://user-images.githubusercontent.com/6359214/64317813-44cc1380-cfeb-11e9-90e0-9f2abc2cdb1d.png)

**Comment by shingohu** [comment]
是我使用上的问题,demo中也有问题,viewmodel会重复创建
这里的UseWebViewPluginModel 在每次build的时候都会重新创建一个
```
ProviderWidget<UseWebViewPluginModel>(
                  model: UseWebViewPluginModel(),
                  builder: (context, model, child) => ListTile(
                    title: Text('WebViewPlugin'),
                    onTap: model.switchValue,
                    leading: Icon(
                      Icons.language,
                      color: iconColor,
                    ),
                    trailing: CupertinoSwitch(
                        activeColor: Theme.of(context).accentColor,
                        value: model.value,
                        onChanged: (value) {
                          model.switchValue();
                        }),
                  )
```

**Comment by phoenixsky** [comment]
viewmodel的重复创建是因为Widget的重新build导致的. 你在ProviderWidget父级打个日志就看出来了.
在debug mode下(注意不是可以断点调试的那个debug),因为flutter框架导致了Widget build了两次.所以导致viewmodel也new了两次
