### ISSUE TITLE
请教下如何让model更加解耦

### ISSUE THREAD

**Issue by liulianshanzhu** [phoenixsky/fun_android_flutter#81]
项目中model除了是数据模型，同时也承担了vm职责。我想剥离其中的业务逻辑，让model只是model，vm（新增）才承担该有的业务逻辑。这个想法有什么好的实现方式吗？

**Comment by phoenixsky** [comment]
你指的是哪个model，model里没什么业务逻辑啊

**Comment by liulianshanzhu** [comment]
抱歉，理解错了。你的vm写的是后缀是model，我以为是数据模型。一开始以为你是用层级嵌套，外层处理业务逻辑，现在理解过来了，XXModel实际上是viewmodel。
