### ISSUE TITLE
ios真机运行报错

### ISSUE THREAD

**Issue by huhu360** [phoenixsky/fun_android_flutter#82]
在iOS上运行一直报错，是否只能运行安卓手机？

**Comment by phoenixsky** [comment]
iOS在AppStore上有上架，可以直接下载体验。
如果运行报错，请贴下log

**Comment by huhu360** [comment]
ent 49047053 bytes  received 7156 bytes  19621683.60 bytes/sec
total size is 48922530  speedup is 1.00
building file list ... done
Flutter.framework/
Flutter.framework/Flutter
Flutter.framework/Info.plist
Flutter.framework/icudtl.dat

sent 97525856 bytes  received 92 bytes  39010379.20 bytes/sec
total size is 97513657  speedup is 1.00
/Users/zwm/Library/Developer/Xcode/DerivedData/Runner-acbelacgochmtwbdkunlcrfcsapi/Build/Products/Debug-iphoneos/Runner.app/Frameworks/App.framework/App: signed bundle with Mach-O universal (x86_64 arm64) [io.flutter.flutter.app]
/Users/zwm/Library/Developer/Xcode/DerivedData/Runner-acbelacgochmtwbdkunlcrfcsapi/Build/Products/Debug-iphoneos/Runner.app/Frameworks/Flutter.framework/Flutter: signed bundle with Mach-O universal (armv7 x86_64 arm64) [io.flutter.flutter]
2020-09-08 17:03:31.677 defaults[16227:229083] 
The domain/default pair of (/Users/zwm/Library/Developer/Xcode/DerivedData/Runner-acbelacgochmtwbdkunlcrfcsapi/Build/Products/Debug-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/Info.plist, CFBundleExecutable) does not exist
fatal error: lipo: can't map input file: /Users/zwm/Library/Developer/Xcode/DerivedData/Runner-acbelacgochmtwbdkunlcrfcsapi/Build/Products/Debug-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/ (Invalid argument)
fatal error: lipo: can't map input file: /Users/zwm/Library/Developer/Xcode/DerivedData/Runner-acbelacgochmtwbdkunlcrfcsapi/Build/Products/Debug-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/ (Invalid argument)
Failed to extract arm64 for /Users/zwm/Library/Developer/Xcode/DerivedData/Runner-acbelacgochmtwbdkunlcrfcsapi/Build/Products/Debug-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/. Running lipo -info:
fatal error: lipo: can't map input file: /Users/zwm/Library/Developer/Xcode/DerivedData/Runner-acbelacgochmtwbdkunlcrfcsapi/Build/Products/Debug-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/ (Invalid argument)
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by huhu360** [comment]
已经安装完pod依赖，提示上面的这些问题，不知道其他人遇到过没

**Comment by huhu360** [comment]
上面的是在xcode上的错误提示，
下面是as上报错内容：
Command PhaseScriptExecution failed with a nonzero exit code
note: Using new build system
note: Planning build
note: Constructing build description
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'FMDB' from project 'Pods')

**Comment by phoenixsky** [comment]
感谢反馈， 我这边跟进一下看看

**Comment by phoenixsky** [comment]
更新了一些插件版本后，我这边可以直接运行了，你pull下代码试试

**Comment by huhu360** [comment]
请问你那边xcode是什么版本的，我这边是xcode11.2，我这边还是报之前的错误，刚接触flutter不知道是不是自己哪里没有配置好

**Comment by phoenixsky** [comment]
我这边xcode 11.7了，11.4好像换了新的build system。
你可以拿Command PhaseScriptExecution failed with a nonzero exit code 去搜索一下

**Comment by huhu360** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "phoenixsky/fun_android_flutter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月8日(星期二) 下午5:45
收件人:&nbsp;"phoenixsky/fun_android_flutter"<fun_android_flutter@noreply.github.com&gt;;
抄送:&nbsp;"虎虎"<670940689@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [phoenixsky/fun_android_flutter] ios真机运行报错 (#82)





 
感谢反馈， 我这边跟进一下看看

**Comment by huhu360** [comment]
非常感谢，已经解决了。
