### ISSUE TITLE
项目运行不起来

### ISSUE THREAD

**Issue by mmyydy** [phoenixsky/fun_android_flutter#87]
AnimationController(vsync: this, duration: Duration(seconds: 4));
这个地方报错 
The named parameter 'vsync' isn't defined. 

main里的                  onGenerateRoute:Router.generateRoute,
 这个也取不到 请问怎么解决

**Comment by AsyncHope** [comment]
问题解决了吗，我也遇到 onGenerateRoute: Router.generateRoute, 报错

**Comment by mmyydy** [comment]
解决了  我把router抽出来自己定义了一下 就可以

**Comment by mmyydy** [comment]
studio的file->invalidate catch并重新打开 我就可以识别这个了

**Comment by mmyydy** [comment]
> ```
>    AnimationController(vsync: this, duration: Duration(seconds: 4));
> ```
> 
> 这个地方报错
> The named parameter 'vsync' isn't defined.
> 
> main里的 onGenerateRoute:Router.generateRoute,
> 这个也取不到 请问怎么解决

studio的file->invalidate catch并重新打开 我就可以识别这个了

**Comment by kingwin0129** [comment]
项目报错清除缓存invalidate重启就基本解决了。
Router报错是因为当前文件里被Import的包里有同名叫Router的文件存在，编译器不确定你使用的是哪个，所以只要在包这边处理下就好了，增加 hide Router就好了
 import 'package:flutter/cupertino.dart' hide Router;
import 'package:flutter/material.dart' hide Router;

**Comment by Leon-ele** [comment]
import 'config/router_manger.dart' as prefix; 即可

**Comment by phoenixsky** [comment]
The named parameter 'vsync' isn't defined.
可以flutter clean后重新打开 android studio / vs
