### ISSUE TITLE
收藏的一个bug

### ISSUE THREAD

**Issue by chenqi5256969** [phoenixsky/fun_android_flutter#9]
我在首页点击收藏A文章，然后去我的->收藏下面取消收藏，但是首页A文章的收藏状态没有发生改变，还是显示收藏状态，这个bug困扰了我很久，找不出解决方法，除非取消with AutomaticKeepAliveClientMixin这句代码，但是如果不保留状态，用户体验会非常糟糕，希望大神可以解决一下这个bug

**Comment by phoenixsky** [comment]
![timg](https://user-images.githubusercontent.com/6359214/64355094-2db11400-d033-11e9-9276-a51575065fbd.jpg)
....这个问题我知道,但是一直没有好的思路.
在native下有什么好的方案么?

如果通过刷新数据的方式来修改`收藏`状态, 就需要找到一个相对合适的时机来刷新数据源.并没有特别合适的时机,(通过直接去除状态的方法太暴力,明显是不合适的)

初步思路是 可以在全局维持一个Map对象,来维护文章`收藏`状态的值.
key为文章id,value为bool类型,true为收藏,false为没有收藏

在我的收藏里,如果修改了文章的收藏状态,可以put一个<id,true/false>的键值对.
 
在其他列表里的`是否收藏` 是先根据这个map里的值,
如果在map里找到了,则取map里对应的值,
如果在map里未找到,则取本身item对象里的值.

**Comment by chenqi5256969** [comment]
做一个通知，怎么样，大神

**Comment by phoenixsky** [comment]
这个问题其实还蛮复杂.要想完美,有几个点需要考虑
这里分为home页(第一个tab页),tab页(第二个tab页面也就是project tab),我的收藏页三个页面

1. 在我的收藏页面取消收藏后,home页和tab页都需要同步未收藏的状态
2. 在首页收藏/取消收藏后,tab页对应的状态也要同步,反之,也是一样
3. 用户切换、登录登出后,home页和tab页的收藏状态需要更新
4. 在其他设备或PC端修改了收藏状态后,home页和tab页都需要在下拉刷新后,同步收藏状态

这两天抽时间实现一下.

有个问题就是功能越完善会导致代码越复杂,不太利于最初项目开源的初衷.
可能会劝退刚接触flutter朋友

**Comment by phoenixsky** [comment]
@chenqi5256969 搞定了,但是`wanandroid`的接口数据有些问题..在别的设备上收藏了文章后,原先设备列表刷新后,收藏状态并不会改变.需要重新登录. 等hongyang修复
