### ISSUE TITLE
你好，windows启动项目一直下载不了包

### ISSUE THREAD

**Issue by Niofh** [phoenixsky/fun_android_flutter#90]
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.
──────────────────────────────────────────────────────────────────────────────

这句话怎么解决呢，百度找好久都不可以

**Comment by phoenixsky** [comment]
签名是旧版本，这个报错对运行不影响。
