### ISSUE TITLE
空安全 迁移有计划吗？大佬

### ISSUE THREAD

**Issue by james-bltg** [phoenixsky/fun_android_flutter#99]
最近dart的2.12 空安全出来了，请问大佬有迁移计划吗？

**Comment by phoenixsky** [comment]
已立项
下个版本会接入`2.x`、`空安全`、`GetX`等
主要是代码架构上的一些优化，app功能本身应该不会有太多变化

**Comment by zhouxin1233** [comment]
> 已立项
> 下个版本会接入`2.x`、`空安全`、`GetX`等
> 主要是代码架构上的一些优化，app功能本身应该不会有太多变化

大佬 空安全和架构上优化 大概什么时候能完成啊，想借鉴下
